version: '2'

vars:
  env_name: minikube
  dump_location: gs://serlo_dev_terraform/sql-dumps/dump-2019-05-13.zip
  athene2_host: https://de.serlo.local/mathe

includes:
  build:    tasks/build.yml
  log:      tasks/log.yml
  minikube: ../infrastructure/tasks/minikube.yml
  terraform: tasks/terraform.yml

tasks:
  default:
    cmds:
      - task -l

  create: 
    desc: |
      *
        - ensures cluster is created
        - deploys the resources
        - launches the website
    cmds: 
      - task: minikube:create
      - task: deploy
      - task: launch

  start:
    desc: |
      *
        - ensures cluster is started
        - launches the website    
    cmds:
      - task: minikube:start
      - task: launch

  deploy:
    desc: |
      *
        - [minikube] builds the images in case they are not present in remote docker
        - applies the resources with terraform
    cmds:
      - task: build:all
      - task: terraform:apply
      - task: upload_athene2_dump

  launch:
    desc: |
      *
        - launches the athene2 web site
        - [minikube] basic auth user and password is serlo
    preconditions:
      - until kubectl logs $(kubectl get pods --namespace athene2 | grep athene2-app | awk '{ print $1 }') -c athene2-php-container --namespace athene2 | grep -q "GET /index.php. 200" ; do echo wait for athene2-app to be ready ; sleep 10 ; done
    cmds:
      - xdg-open {{.athene2_host}} 2>/dev/null >/dev/null

  download_athene2_dump:
    cmds:
      - mkdir -p tmp && echo "downloading latest mysql dump from gcloud" && gsutil cp {{.dump_location}} tmp/dump.zip
      - unzip tmp/dump.zip -d tmp
    status:
      - test -f tmp/dump.sql

  upload_athene2_dump:
    deps: [download_athene2_dump]
    cmds:
      - bash scripts/setup-athene2-db.sh
