version: '2'

vars:
  namespace: athene2

tasks:
  dbsetup:
    desc: |
      *
        - show dbsetup pod log and follow the output
    cmds:
      - task: kubectl_use_context
      - kubectl logs $(kubectl get pods --namespace {{.namespace}} | grep ^dbsetup-cronjob | awk '{ print $1 }') --all-containers=true --namespace {{.namespace}} --follow

  athene2_app:
    desc: |
      *
        - show athene2 pod log and follow the output
    cmds:
      - task: kubectl_use_context
      - kubectl logs $(kubectl get pods --namespace athene2 | grep ^athene2-app | awk '{ print $1 }') --all-containers=true --namespace {{.namespace}} --follow

  editor:
    desc: |
      *
        - show athene2 pod log and follow the output
    cmds:
      - task: kubectl_use_context
      - kubectl logs $(kubectl get pods --namespace athene2 | grep ^editor-renderer | awk '{ print $1 }') --all-containers=true --namespace {{.namespace}} --follow

  legacy_editor:
    desc: |
       *
         - show legacy editor pod log and follow the output
    cmds:
      - task: kubectl_use_context
      - kubectl logs $(kubectl get pods --namespace athene2 | grep ^legacy-editor-renderer | awk '{ print $1 }') --all-containers=true --namespace {{.namespace}} --follow

  kubectl_use_context:
    desc: |
      *
        - switch kubectl context
    cmds:
      - kubectl config use-context minikube
